// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmDFk69yDSGs3ZlS8F1iJHzbS_Z5hVm24',
    appId: '1:240177305801:web:3966471b3f7443e83b5518',
    messagingSenderId: '240177305801',
    projectId: 'ziad-e5a5d',
    authDomain: 'ziad-e5a5d.firebaseapp.com',
    storageBucket: 'ziad-e5a5d.firebasestorage.app',
    measurementId: 'G-W060Q0ZYTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRxy2goS4N-I1Kcl98X-tLP9SzWLA2Yyg',
    appId: '1:240177305801:android:634e0b78b5bc2d5c3b5518',
    messagingSenderId: '240177305801',
    projectId: 'ziad-e5a5d',
    storageBucket: 'ziad-e5a5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4TPLq-MFgOHIDdAvHImYBAaFxVyX9sSE',
    appId: '1:240177305801:ios:965fe05056b6e5963b5518',
    messagingSenderId: '240177305801',
    projectId: 'ziad-e5a5d',
    storageBucket: 'ziad-e5a5d.firebasestorage.app',
    iosBundleId: 'com.example.yumQuick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4TPLq-MFgOHIDdAvHImYBAaFxVyX9sSE',
    appId: '1:240177305801:ios:965fe05056b6e5963b5518',
    messagingSenderId: '240177305801',
    projectId: 'ziad-e5a5d',
    storageBucket: 'ziad-e5a5d.firebasestorage.app',
    iosBundleId: 'com.example.yumQuick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmDFk69yDSGs3ZlS8F1iJHzbS_Z5hVm24',
    appId: '1:240177305801:web:37ff00d562f4d3063b5518',
    messagingSenderId: '240177305801',
    projectId: 'ziad-e5a5d',
    authDomain: 'ziad-e5a5d.firebaseapp.com',
    storageBucket: 'ziad-e5a5d.firebasestorage.app',
    measurementId: 'G-6Z2BHNT9LE',
  );
}
